server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Tenta carregar o arquivo ou diretório; se não achar, envia para o index.html
        try_files $uri $uri/ /index.html;
    }

    # Cache e otimização para arquivos estáticos
    location ~ \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        root /usr/share/nginx/html;
        expires max;
        log_not_found off;
    }
}